package com.richaa2.map.kmp.presentation.map.utils

const val CLUSTER_ANIMATION_ZOOM_DURATION_MS = 500
const val ANIMATION_TO_CURRENT_LOCATION_DURATION_MS = 1000
const val UPDATE_LOCATION_INTERVAL_MS = 10000L
const val MIN_UPDATE_LOCATION_INTERVAL_MS = 5000L
const val DEFAULT_ZOOM_LEVEL = 15f
const val DEFAULT_MAP_PADDING = 100.0
const val DEFAULT_MAP_LATITUDE = 49.842957
const val DEFAULT_MAP_LONGITUDE = 24.031111